<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dizido.Client\Dizido.Client.csproj" />
    <ProjectReference Include="..\Dizido.Contracts\Dizido.Contracts.csproj" />
  </ItemGroup>

</Project>
